[tool.poetry]
name = "task"
version = "0.1.0"
description = ""
authors = ["Author <author@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<4"
uvicorn = "^0.23.2"
httpx = "^0.27.0"
fastapi = "^0.115.6"
sqlalchemy = "^2.0.37"
asyncpg = "^0.30.0"
alembic = "^1.14.0"
pydantic-settings = "^2.7.0"
celery = "^5.4.0"
redis = "^5.2.0"
aiokafka = "^0.14.0"
fastavro = "^1.10.0"
clickhouse-connect = "^0.8.7"
dependency-injector = "^4.48.0"
loguru = "^0.7.3"
email-validator = "^2.3.0"


[tool.poetry.group.dev.dependencies]
faker = "^19.10.0"
pytest = "^8.3.0"
pytest-alembic = "^0.10.7"
pytest-asyncio = "^0.24.0"
pytest-cov = "^4.1.0"
pytest-env = "^1.0.1"
pytest-httpx = "^0.31.2"
pytest-mock = "^3.11.1"
pytest-mock-server = "^0.3.0"
pytest-xdist = "^3.3.1"
mypy = "^1.13.0"
ruff = "^0.8.0"
isort = "^5.13.2"
pre-commit = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = "120"
